# Generated by Django 4.1.2 on 2022-11-04 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nume', models.CharField(max_length=50)),
                ('trailer', models.URLField()),
                ('gen', models.CharField(max_length=50)),
                ('descriere', models.TextField()),
                ('timp', models.CharField(max_length=50)),
                ('an', models.CharField(max_length=50)),
                ('locuri', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rezervare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locuri', models.CharField(max_length=50)),
                ('film', models.CharField(max_length=50)),
                ('tip', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=50)),
            ],
        ),
    ]
