# Generated by Django 4.1.2 on 2023-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0003_alter_rezervare_locuri'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='nume_de_familie',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rezervare',
            name='prenume',
            field=models.CharField(default='', max_length=50),
        ),
    ]
