# Generated by Django 4.1.2 on 2023-01-31 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0004_rezervare_nume_de_familie_rezervare_prenume'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='email',
            field=models.EmailField(default='', max_length=254, verbose_name=''),
        ),
    ]
