# Generated by Django 4.1.2 on 2023-02-01 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0005_rezervare_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='rezervare',
            name='cvv2',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rezervare',
            name='data_expirare_card',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='rezervare',
            name='numar_card',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='rezervare',
            name='email',
            field=models.EmailField(default='', max_length=100),
        ),
    ]
