# Generated by Django 4.1.2 on 2023-03-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0006_rezervare_cvv2_rezervare_data_expirare_card_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='recomandari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prenume', models.CharField(max_length=1550)),
                ('nume_de_familie', models.CharField(max_length=1550)),
                ('email', models.CharField(max_length=1550)),
                ('subiect', models.CharField(max_length=1550)),
            ],
        ),
    ]
