# Generated by Django 4.1.2 on 2023-04-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0007_recomandari'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'verbose_name_plural': '1. Filme'},
        ),
        migrations.AlterModelOptions(
            name='recomandari',
            options={'verbose_name_plural': '3. Recomandări'},
        ),
        migrations.AlterModelOptions(
            name='rezervare',
            options={'verbose_name_plural': '2. Rezervări/Cumpărări'},
        ),
        migrations.AddField(
            model_name='recomandari',
            name='data',
            field=models.CharField(default='', max_length=50),
        ),
    ]
