# Generated by Django 4.1.2 on 2023-04-24 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bacend', '0008_alter_film_options_alter_recomandari_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recomandari',
            name='data',
        ),
    ]
